### ISSUE TITLE
Not showing up in script list

### ISSUE THREAD

**Issue by rszanto** [dfaker/stable-diffusion-webui-cv2-external-masking-script#1]
After running the install command and placing the .py file in the main scripts folder, it still doesn't appear in the GUI's dropdown menu.  Is there an additional step that's missing?  Thanks!

**Comment by dfaker** [comment]
That should be it, it should appear in the listings in img2img after restarting.

If not, do we receive any errors in the terminal?

**Comment by daviddwalton** [comment]
The script is also not showing up in the script list for me. When I run AUTOMATIC1111's webui (webui-user.bat) I get the following error:

Traceback (most recent call last):
  File "D:\Apps\stable-diffusion-webui\modules\scripts.py", line 69, in load_scripts
    compiled = compile(text, path, 'exec')
  File "D:\Apps\stable-diffusion-webui\scripts\external_masking.py", line 68
    <title>stable-diffusion-webui-cv2-external-masking-script/external_masking.py at main · dfaker/stable-diffusion-webui-cv2-external-masking-script · GitHub</title>
                                                                                          ^
SyntaxError: invalid character '·' (U+00B7)

Any ideas?

**Comment by dfaker** [comment]
@mrwally you've downloaded the html of the webpage not the script, try: https://raw.githubusercontent.com/dfaker/stable-diffusion-webui-cv2-external-masking-script/main/external_masking.py
