### ISSUE TITLE
[BUG] It is end of Automatic1111 repo - 404 on GitHub

### ISSUE THREAD

**Issue by Rogal80** [dfaker/stable-diffusion-webui-cv2-external-masking-script#16]
Hi, is it ended, or just some issues? 

https://github.com/AUTOMATIC1111/stable-diffusion-webui
![image](https://user-images.githubusercontent.com/112553453/210773450-d3c95f0e-a5b9-43ca-ad83-b77adb24c651.png)

**Comment by dfaker** [comment]
Most likely a bug with github as I'm still able to sync my fork through the ui: https://github.com/dfaker/stable-diffusion-webui

**Comment by dfaker** [comment]
Seemingly not: https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui

**Comment by Rogal80** [comment]
ok thx for info - i was worry :(
