### ISSUE TITLE
How can I install this - I am just an artist (:

### ISSUE THREAD

**Issue by Rogal80** [dfaker/stable-diffusion-webui-cv2-external-masking-script#5]
hi, I have issue when run webui after "my way of installation" 
![image](https://user-images.githubusercontent.com/112553453/194513365-1d793208-4d4f-4b4a-a9fc-d7dae58df399.png)

i just run command that was in instruction and then paste script in folder scripts of Web UI , after that its showing this issue and there is no additional script in img2img
![image](https://user-images.githubusercontent.com/112553453/194513840-a067ccb4-5124-4166-aec1-4eb05114da72.png)

**Comment by dfaker** [comment]
I'll put a note on the main page, you've downloaded the webpage, not the script.

Get it in a zip file here: https://github.com/dfaker/stable-diffusion-webui-cv2-external-masking-script/archive/refs/heads/main.zip

**Comment by Rogal80** [comment]
fixed :) thx

**Comment by Rogal80** [comment]
its awesome :):):):):):)
