### ISSUE TITLE
No window opens to edit mask

### ISSUE THREAD

**Issue by nixudos** [dfaker/stable-diffusion-webui-cv2-external-masking-script#6]
I have installed CV2 and put the script in the scipts folder, but no edit window shows?
What is the order of adding the image to be masked? I tried choosing script first and uploading image first.
I'm on a PC, using a chrome browser in incognito mode.

**Comment by dfaker** [comment]
The script will need to be selected, add the mask whenever, and then the window will appear after you click generate.

Let me know if you have any error messages at that point.

**Comment by nixudos** [comment]
Great! That works.
Thanks :-)

**Comment by dfaker** [comment]
Great!
