### ISSUE TITLE
Generation information not showing when using custom script

### ISSUE THREAD

**Issue by VantomPayne** [dfaker/stable-diffusion-webui-cv2-external-masking-script#8]
Hello, first of all, thanks for this wonderful script, have been using it since it came out!
But there has always been a problem, while this script is activated, the generation information does not show up in the right bottom corner of the inpainting UI, this is not the case when generate again after closing the script. 
I do not know if this is the case for all custom script or just this one as this is the only script I've been using, it would be great if you could take a look, thanks!

![image](https://user-images.githubusercontent.com/75436865/196041753-9e9dba4a-0d50-44d5-b0f9-dda7e7e9b012.png)
↑when not activated.

![image](https://user-images.githubusercontent.com/75436865/196041790-c27d290c-385c-49a7-8be8-e31aac9f3c1a.png)
↑when activated

**Comment by VantomPayne** [comment]
Just to add some information, the reuse seed function and history tab both do not work with the script enabled, and saving one image out of a batch gives an index error, I think these all possibly point to a conflict with the generation info feature, since I assume saving 1 image out of a batch would attempt to pull the seed # to rename the images.

**Comment by dfaker** [comment]
Okay, that's now passing the full details from the last process_images response.
